In [1]:
import numpy

In [2]:
import cv2

In [15]:
img = cv2.imread("100 smallgray.png",0)

In [4]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
img = cv2.imread("100 smallgray.png",1)

In [21]:
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [22]:
cv2.imwrite("Newimage.png",img)

True

In [23]:
img = cv2.imread("100 smallgray.png",0)

In [24]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
img[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [29]:
img[0:1,0:4]

array([[187, 158, 104, 121]], dtype=uint8)

In [31]:
img[1,4]

147